### ISSUE TITLE
Pre-Processing for MediaPipe

### ISSUE THREAD

**Issue by hshreeshail** [sign-language-processing/detection-train#4]
I gather that there are multiple pre-processing steps that happen on the MediaPipe Holistic output. Stuff like 
1] identifying keypoints that are not present in frame t (so that the keypoint's flow for frame t & t+1 can be set to 0)
2] Normalizing the pose_landmarks, left_hand_landmarks, right_hand_landmarks values so that the "mean-distance between the shoulders is 1".
Could you point me out to the exact file which contains the code for these steps?

Also, in pre-processing step-2 (as presented above), what is the mean calculated over? Over different frames from a single video? Over the entire dataset? 
What does this imply for test time processing since there we only see one frame at a time? At test time, should we just normalize so that the distance between shoulders in that frame is 1?

**Comment by AmitMY** [comment]
Missing poses are just `False` on a `numpy.MaskedArray`.

The optical flow calculation is here: https://github.com/sign-language-processing/detection-train/blob/master/sign_language_detection/dataset.py#L48

There should be another step for shoulder normalization, though it seems to be missing. 
Should probably re-add it when creating the tfrecord dataset:
```
pose.normalize(pose.header.normalization_info(
  p1=("POSE_LANDMARKS", "RIGHT_SHOULDER"),
  p2=("POSE_LANDMARKS", "LEFT_SHOULDER")
))
```

The shoulder width is calculated over the entire video, but in inference time, I found that looking at the average of the last 20 frames works. You can look at the application code.

**Comment by hshreeshail** [comment]
Thanks for the response. I had another query. For a given keypoint, when using the MediaPipe Holistic co-ordinates to calculate flow, do you use the 2D co-ordinates i.e., (x,y) or the 3D co-ordinates i.e., (x,y,z)?
Asking since the holistic documentation [here](https://google.github.io/mediapipe/solutions/holistic.html#pose_landmarks) suggests that the `z` value of `pose_landmarks` should be discarded.

**Comment by AmitMY** [comment]
You are correct.
I have redone the `dgs` code - https://github.com/sign-language-processing/detection-train/commit/fcbbb982a85dd8849e3557b5e3adfac03ed9fb29

That should get better results, however, it was not tested - as in no model was trained using it yet
