### ISSUE TITLE
Potential bug in extracting labels from sign glosses

### ISSUE THREAD

**Issue by hshreeshail** [sign-language-processing/detection-train#5]
I think there is a bug in the [`create_tfrecord_dgs_corpus.py`](https://github.com/sign-language-processing/detection-train/blob/master/sign_language_detection/examples/create_tfrecord_dgs_corpus.py#L63). I am not 100% sure, because I haven't run the file itself, since the `tfds.load('dgs_corpus')` line takes very long to run on my machine. But I needed to use some code from this in another place, and I had to modify it as follows:
I think the assignment `sentences = get_elan_sentences(elan_path)` line should be inside [this](https://github.com/sign-language-processing/detection-train/blob/master/sign_language_detection/examples/create_tfrecord_dgs_corpus.py#L65) for loop (`for person in ["a", "b"]:`). Because, the `sentences` variable of type `<class 'generator'>` yields all its values in the first iteration (i.e., iteration of person "a"), it has no more values to yield for the iteration of person "b" and hence, should be re-assigned in this iteration. For this reason, it must be assigned inside the for loop instead of outside.

Do correct me if I am wrong.

**Comment by AmitMY** [comment]
so the file does indeed run well, but you do have a point.
I added a `list` casting, just in case.

**Comment by bricksdont** [comment]
@Shreeshail-Hingane good catch, thank you!
